* Structs
** complex - need unloading
- [ ] Music
- [ ] Sound
- [ ] Wave
- [X] Shader
- [X] Material
- [X] Mesh
- [X] Model
- [X] Font
- [X] Image
- [X] Texture2D / Texture
- [X] RenderTexture2D / RenderTexture
** complex - other
- AudioStream (see CloseAudioStream)
- MaterialMap
- CharInfo
** simple
- Color
- Rectangle
- Vector2
- Vector3
- Vector4
- Quaternion
- Matrix
- Camera (Vector3)
- Camera2D (Vector2)
- Ray (Vector3)
- RayHitInfo (Vector3)
* Storable example
Remember: there is a Vector2 struct in raylib.h

data Vector2 = Vector2 Float Float

instance Storable Vector2 where
    sizeOf = const {# sizeof Vector2 #}
    alignment = const {# alignof Vector2 #}
    peek p = do
        x <- realToFrac <$> {# get Vector2.x #} p
        y <- realToFrac <$> {# get Vector2.y #} p
        pure $ Vector2 x y
    poke p (Vector2 x y) = do
        {# set Vector2.x #} p (realToFrac x)
        {# set Vector2.y #} p (realToFrac y)
* Image pointer example
{# pointer *Image foreign finalizer WrappedUnloadImage as unloadImage newtype #}

imageWidth :: Image -> IO Int
imageWidth image = fromIntegral <$> withForeignPtr (coerce image) width
  where width = {# get Image.width #}

imageHeight :: Image -> IO Int
imageHeight image = fromIntegral <$> withForeignPtr (coerce image) height
  where height = {# get Image.height #}
* Bind plan
** Plan
- [X] Review Haddock format.

- [X] Identify all the structs used in the public raylib API.

- [X] Classify those structs as simple, or complex. Complex structs are either unloadable or in a special category. Most of this work has been done, and just needs review.

- [X] Create Storable bindings for simple structs.

- [ ] Create pointer newtype bindings for complex unloadable structs.

- [ ] Bind Core, and Shapes.

- [ ] Release. Seek feedback.

- [ ] Bind the remaining modules.

- [ ] Improve inspectability of complex structs.
** Project layout
Modules:
- Structs / Types
- Core
- Shapes
- Textures
- Text
- Models
- Shaders
- Audio

Each module will have a "public" version with some Haskell cleanups, and an "Internal" version with c2hs binding code.
** Cleanups
- [X] sizeOf _ = {# sizeof X #} is more clear than sizeOf = const {# sizeof X #}; replace the definitions.
- [X] Put strict annotations on all the data fields.
- [X] Double check derived instances on data types. We should probably have Show and Eq on all datatypes.
- [ ] Finish creating field accessors for basic data types.
- [ ] Review and improve documentation
- [ ] Create a data type for the type value in Camera3D.
- [ ] Create accessors for complex types
- [ ] Bind complex sound types
